// Layer 3 Tool — Test Plan: build prompt, call GROQ, render deterministic Markdown.
// Boundary rule (BLAST): GROQ produces CONTENT (JSON); Markdown rendering is deterministic code.
// Ported from Pramod's repo.
import { groqChat } from './groqClient.js';

const SCHEMA_HINT = `Return ONLY a JSON object with EXACTLY these keys:
{
  "testPlanId": string,                 // e.g. "TP-<KEY>"
  "sourceIssue": string,                // the Jira key
  "title": string,                      // "Test Plan — <summary>"
  "objective": string,
  "scope": { "inScope": string[], "outOfScope": string[] },
  "inclusions": string[],
  "testEnvironments": string[],
  "defectReporting": string,
  "testStrategy": string[],
  "schedule": [ { "phase": string, "owner": string, "dates": string } ],
  "deliverables": string[],
  "entryCriteria": string[],
  "exitCriteria": string[],
  "tools": string[],
  "risks": [ { "risk": string, "mitigation": string } ],
  "approvals": [ { "role": string, "name": string } ]
}`;

export function buildMessages(issue) {
  const system = [
    'You are a senior QA Lead writing a FORMAL software Test Plan.',
    'Base everything strictly on the provided Jira issue.',
    'If information is missing, use "TBD" — never invent specific facts (names, dates, versions).',
    'Be concrete, professional, and concise. Output strictly valid JSON.',
  ].join(' ');

  const user = [
    'Create a formal Test Plan for the following Jira issue.',
    '',
    `Key: ${issue.key}`,
    `Summary: ${issue.summary}`,
    `Type: ${issue.issueType} | Status: ${issue.status} | Priority: ${issue.priority}`,
    `Components: ${issue.components.join(', ') || 'none'}`,
    `Labels: ${issue.labels.join(', ') || 'none'}`,
    `Fix Versions: ${issue.fixVersions.join(', ') || 'none'}`,
    `Reporter: ${issue.reporter} | Assignee: ${issue.assignee || 'Unassigned'}`,
    '',
    'Description / Acceptance Criteria:',
    issue.description || '(no description provided)',
    '',
    SCHEMA_HINT,
  ].join('\n');

  return [
    { role: 'system', content: system },
    { role: 'user', content: user },
  ];
}

/**
 * Call GROQ to generate the test plan JSON, then parse it.
 */
export async function generateTestPlan(config, issue) {
  const messages = buildMessages(issue);
  const raw = await groqChat(config, messages);
  try {
    return JSON.parse(raw);
  } catch {
    throw new Error('GROQ returned invalid JSON for the Test Plan. Raw output:\n' + raw.slice(0, 500));
  }
}

/**
 * Deterministic Markdown rendering from the structured plan JSON.
 */
export function renderMarkdown(plan) {
  const lines = [];
  const ln = (s = '') => lines.push(s);
  const list = (arr) => (arr || []).forEach((i) => ln(`- ${i}`));
  const table = (cols, rows, cells) => {
    ln(`| ${cols.join(' | ')} |`);
    ln(`| ${cols.map(() => '---').join(' | ')} |`);
    (rows || []).forEach((r) => ln(`| ${cells(r).join(' | ')} |`));
  };

  ln(`# ${plan.title || 'Test Plan'}`);
  ln();
  ln(`**Plan ID:** ${plan.testPlanId || 'TBD'}  `);
  ln(`**Source Issue:** ${plan.sourceIssue || 'TBD'}`);
  ln();

  ln('## 1. Objective');
  ln(plan.objective || 'TBD');
  ln();

  ln('## 2. Scope');
  ln('### In Scope');
  list(plan.scope?.inScope);
  ln('### Out of Scope');
  list(plan.scope?.outOfScope);
  ln();

  ln('## 3. Inclusions');
  list(plan.inclusions);
  ln();

  ln('## 4. Test Environments');
  list(plan.testEnvironments);
  ln();

  ln('## 5. Defect Reporting');
  ln(plan.defectReporting || 'TBD');
  ln();

  ln('## 6. Test Strategy');
  list(plan.testStrategy);
  ln();

  ln('## 7. Schedule');
  table(['Phase', 'Owner', 'Dates'], plan.schedule, (r) => [r.phase, r.owner, r.dates]);
  ln();

  ln('## 8. Deliverables');
  list(plan.deliverables);
  ln();

  ln('## 9. Entry Criteria');
  list(plan.entryCriteria);
  ln();

  ln('## 10. Exit Criteria');
  list(plan.exitCriteria);
  ln();

  ln('## 11. Tools');
  list(plan.tools);
  ln();

  ln('## 12. Risks & Mitigations');
  table(['Risk', 'Mitigation'], plan.risks, (r) => [r.risk, r.mitigation]);
  ln();

  ln('## 13. Approvals');
  table(['Role', 'Name'], plan.approvals, (r) => [r.role, r.name]);
  ln();

  ln('---');
  ln(`*Generated by JIRA Agent (B.L.A.S.T.) on ${new Date().toISOString().slice(0, 10)}*`);

  return lines.join('\n');
}
